let nameList = [
    "Time",
    "Past",
    "Future",
    "Dev",
    "Fly",
    "Flying",
    "Soar",
    "Soaring",
    "Power",
    "Falling",
    "Fall",
    "Jump",
    "Cliff",
    "Mountain",
    "Rend",
    "Red",
    "Blue",
    "Green",
    "Yellow",
    "Gold",
    "Demon",
    "Demonic",
    "Panda",
    "Cat",
    "Kitty",
    "Kitten",
    "Zero",
    "Memory",
    "Trooper",
    "XX",
    "Bandit",
    "Fear",
    "Light",
    "Glow",
    "Tread",
    "Deep",
    "Deeper",
    "Deepest",
    "Mine",
    "Your",
    "Worst",
    "Enemy",
    "Hostile",
    "Force",
    "Video",
    "Game",
    "Donkey",
    "Mule",
    "Colt",
    "Cult",
    "Cultist",
    "Magnum",
    "Gun",
    "Assault",
    "Recon",
    "Trap",
    "Trapper",
    "Redeem",
    "Code",
    "Script",
    "Writer",
    "Near",
    "Close",
    "Open",
    "Cube",
    "Circle",
    "Geo",
    "Genome",
    "Germ",
    "Spaz",
    "Shot",
    "Echo",
    "Beta",
    "Alpha",
    "Gamma",
    "Omega",
    "Seal",
    "Squid",
    "Money",
    "Cash",
    "Lord",
    "King",
    "Duke",
    "Rest",
    "Fire",
    "Flame",
    "Morrow",
    "Break",
    "Breaker",
    "Numb",
    "Ice",
    "Cold",
    "Rotten",
    "Sick",
    "Sickly",
    "Janitor",
    "Camel",
    "Rooster",
    "Sand",
    "Desert",
    "Dessert",
    "Hurdle",
    "Racer",
    "Eraser",
    "Erase",
    "Big",
    "Small",
    "Short",
    "Tall",
    "Sith",
    "Bounty",
    "Hunter",
    "Cracked",
    "Broken",
    "Sad",
    "Happy",
    "Joy",
    "Joyful",
    "Crimson",
    "Destiny",
    "Deceit",
    "Lies",
    "Lie",
    "Honest",
    "Destined",
    "Bloxxer",
    "Hawk",
    "Eagle",
    "Hawker",
    "Walker",
    "Zombie",
    "Sarge",
    "Capt",
    "Captain",
    "Punch",
    "One",
    "Two",
    "Uno",
    "Slice",
    "Slash",
    "Melt",
    "Melted",
    "Melting",
    "Fell",
    "Wolf",
    "Hound",
    "Legacy",
    "Sharp",
    "Dead",
    "Mew",
    "Chuckle",
    "Bubba",
    "Bubble",
    "Sandwich",
    "Smasher",
    "Extreme",
    "Multi",
    "Universe",
    "Ultimate",
    "Death",
    "Ready",
    "Monkey",
    "Elevator",
    "Wrench",
    "Grease",
    "Head",
    "Theme",
    "Grand",
    "Cool",
    "Kid",
    "Boy",
    "Girl",
    "Vortex",
    "Paradox",
];

let messages = [
    "Relax your shoulders and let go of tension.",
    "Take deep breaths to calm your mind and body.",
    "Close your eyes and focus on the present moment.",
    "Feel the weight of your body sinking into the massage table.",
    "Release any thoughts or worries from your mind.",
    "Allow yourself to fully unwind and relax.",
    "Imagine yourself in a peaceful, serene environment.",
    "Let the soothing music melt away any stress or anxiety.",
    "Visualize a wave of relaxation washing over you.",
    "Notice any areas of tension in your body and breathe into them.",
    "Feel the warmth of the massage oil on your skin.",
    "Surrender to the healing touch of the massage therapist.",
    "Trust that your body knows how to heal itself.",
    "Picture a soft golden light surrounding you, bringing comfort and peace.",
    "Focus on the sensation of the massage strokes, one at a time.",
    "Allow yourself to be nurtured and cared for.",
    "Picture tension leaving your body with each exhale.",
    "Imagine yourself floating on a cloud, weightless and free.",
    "Feel the gentle pressure of the massage therapist's hands.",
    "Notice how your breath deepens as you relax.",
    "Picture a waterfall washing away any stress or tension.",
    "Let go of any need to control or resist.",
    "Visualize your muscles becoming loose and supple.",
    "Imagine a warm blanket of comfort enveloping you.",
    "Feel gratitude for this time to nurture yourself.",
    "Picture yourself walking through a peaceful forest, surrounded by nature.",
    "Release any expectations and simply be in the moment.",
    "Imagine a gentle breeze carrying away any worries.",
    "Feel the connection between your mind, body, and spirit.",
    "Visualize a garden of tranquility blooming within you.",
    "Let the soothing sounds of nature calm your mind.",
    "Picture yourself cocooned in a cocoon of relaxation.",
    "Imagine waves of relaxation spreading from your head to your toes.",
    "Release any tightness in your jaw and allow it to hang loose.",
    "Visualize your muscles melting like warm wax.",
    "Feel a sense of lightness and ease spreading through your body.",
    "Picture yourself floating on a calm, serene lake.",
    "Allow yourself to receive the healing energy of the universe.",
    "Imagine a warm hug enveloping you with love and comfort.",
    "Visualize a stream of golden light flowing through your body.",
    "Feel tension melting away with each passing moment.",
    "Picture yourself lying on a beach, feeling the warmth of the sun on your skin.",
    "Release any resistance and surrender to the present moment.",
    "Imagine a soft rain washing away any stress or negativity.",
    "Feel the ground supporting you, providing stability and grounding.",
    "Visualize your body becoming a vessel of peace and serenity.",
    "Picture yourself floating among the stars, weightless and serene.",
    "Allow yourself to be fully present in your body.",
    "Feel the energy flowing freely through your body.",
    "Visualize a warm glow radiating from your heart center.",
    "Imagine yourself surrounded by a bubble of calm and tranquility.",
    "Release any need to rush or hurry.",
    "Picture tension unraveling like a ball of yarn.",
    "Feel the sensation of the massage strokes lulling you into relaxation.",
    "Visualize yourself surrounded by a circle of loving support.",
    "Imagine a warm embrace from someone you love.",
    "Let go of any self-judgment or criticism.",
    "Picture yourself walking barefoot on soft grass, feeling grounded and connected.",
    "Feel the gentle rhythm of your breath as it flows in and out.",
    "Visualize a warm, glowing light at the center of your being.",
    "Imagine yourself floating in a pool of warm, soothing water.",
    "Release any tension you're holding in your hands and fingers.",
    "Picture yourself drifting off into a peaceful sleep.",
    "Feel the tension melting away from your neck and shoulders.",
    "Visualize a fountain of youth replenishing your energy.",
    "Imagine a warm cup of tea soothing your soul.",
    "Allow yourself to be cradled by the earth beneath you.",
    "Picture yourself surrounded by a soft, comforting glow.",
    "Feel the gentle rhythm of your heartbeat.",
    "Visualize yourself dancing freely and joyfully.",
    "Imagine a warm fire melting away any stress or tension.",
    "Release any tightness in your chest and allow your heart to open.",
    "Feel the support of the massage table beneath you.",
    "Picture yourself floating on a cloud of relaxation.",
    "Allow yourself to be held in the arms of love.",
    "Visualize a garden of peace flourishing within you.",
    "Imagine a warm breeze carrying away any worries or cares.",
    "Feel the tension leaving your body with each exhale.",
    "Picture yourself basking in the warmth of the sun.",
    "Release any thoughts that no longer serve you.",
    "Visualize a stream of light washing over you, cleansing and renewing.",
    "Imagine yourself surrounded by a bubble of protection.",
    "Feel the gentle touch of the massage therapist's hands.",
    "Picture yourself lying in a field of flowers, soaking up the sunshine.",
    "Allow yourself to be cradled by the earth beneath you.",
    "Visualize a warm, golden light filling your entire being.",
    "Imagine tension melting away like snow in the sun.",
    "Feel the gentle sway of your body as you breathe.",
    "Picture yourself floating on a calm, tranquil lake.",
    "Release any resistance and surrender to the present moment.",
    "Visualize a river of peace flowing through your body.",
    "Imagine yourself surrounded by a circle of love and support.",
    "Feel the tension melting away with each breath.",
    "Picture yourself surrounded by a warm, comforting glow.",
    "Allow yourself to be fully present in this moment.",
    "Visualize a soft rain washing away any stress or tension.",
    "Imagine a warm hug enveloping you with love and comfort.",
    "Feel the warmth of the massage oil soothing your skin.",
    "Picture yourself surrounded by a bubble of calm and tranquility.",
    "Release any need to rush or hurry.",
    "Visualize tension unraveling like a ball of yarn.",
    "Imagine a warm embrace from someone you love.",
    "Feel the gentle rhythm of your breath as it flows in and out.",
    "Picture yourself walking barefoot on soft grass, feeling grounded and connected.",
    "Visualize a warm, glowing light at the center of your being.",
    "Imagine yourself floating in a pool of warm, soothing water.",
    "Release any tension you're holding in your hands and fingers.",
    "Picture yourself drifting off into a peaceful sleep.",
    "Feel the tension melting away from your neck and shoulders.",
    "Visualize a fountain of youth replenishing your energy.",
    "Imagine a warm cup of tea soothing your soul.",
    "Allow yourself to be cradled by the earth beneath you.",
    "Picture yourself surrounded by a soft, comforting glow.",
    "Feel the gentle rhythm of your heartbeat.",
    "Visualize yourself dancing freely and joyfully.",
    "Imagine a warm fire melting away any stress or tension.",
    "Release any tightness in your chest and allow your heart to open.",
    "Feel the support of the massage table beneath you.",
    "Picture yourself floating on a cloud of relaxation.",
    "Allow yourself to be held in the arms of love.",
    "Visualize a garden of peace flourishing within you.",
    "Imagine a warm breeze carrying away any worries or cares.",
    "Feel the tension leaving your body with each exhale.",
    "Picture yourself basking in the warmth of the sun.",
    "Release any thoughts that no longer serve you.",
    "Visualize a stream of light washing over you, cleansing and renewing.",
    "Imagine yourself surrounded by a bubble of protection.",
    "Feel the gentle touch of the massage therapist's hands.",
    "Picture yourself lying in a field of flowers, soaking up the sunshine.",
    "Allow yourself to be cradled by the earth beneath you.",
    "Visualize a warm, golden light filling your entire being.",
    "Imagine tension melting away like snow in the sun.",
    "Feel the gentle sway of your body as you breathe.",
    "Picture yourself floating on a calm, tranquil lake.",
    "Release any resistance and surrender to the present moment.",
    "Visualize a river of peace flowing through your body.",
    "Imagine yourself surrounded by a circle of love and support.",
    "Feel the tension melting away with each breath.",
    "Picture yourself surrounded by a warm, comforting glow.",
    "Allow yourself to be fully present in this moment.",
    "Visualize a soft rain washing away any stress or tension.",
    "Imagine a warm hug enveloping you with love and comfort.",
    "Feel the warmth of the massage oil soothing your skin.",
];

export const generateRandomName = () => nameList[Math.floor(Math.random() * nameList.length)];

export const generateRandomMassage = () => messages[Math.floor(Math.random() * messages.length)];
